codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default:
        target: auto
        threshold: 0%
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 0%
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/*.config.mjs"
  - "**/types/**"
  - "**/__tests__/**"
  - "**/test-utils.ts"
  - "**/vitest.setup.ts"
  - "e2e/**"
  - "scripts/**"
  - "public/**"
  - ".next/**"
  - "out/**"
  - "coverage/**"
  - "src/instrumentation*.ts"
  - "src/app/global-error.tsx"
  - "src/app/sentry-example-page/**"
  - "**/index.ts"
