module.exports = {
	apps: [
		{
			name: 'blackmagickops-dev',
			script: 'pnpm',
			args: 'dev',
			cwd: './',
			interpreter: 'none',
			watch: false,
			env: {
				NODE_ENV: 'development',
				PORT: 3001,
			},
			error_file: './logs/pm2-error.log',
			out_file: './logs/pm2-out.log',
			log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
			merge_logs: true,
			autorestart: true,
			max_restarts: 10,
			min_uptime: '10s',
			restart_delay: 4000,
		},
		{
			name: 'blackmagickops-prod',
			script: 'pnpm',
			args: 'start',
			cwd: './',
			interpreter: 'none',
			instances: 1,
			exec_mode: 'cluster',
			watch: false,
			env: {
				NODE_ENV: 'production',
				PORT: 3000,
			},
			error_file: './logs/pm2-prod-error.log',
			out_file: './logs/pm2-prod-out.log',
			log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
			merge_logs: true,
			autorestart: true,
			max_memory_restart: '500M',
		},
	],
};
